version: '3'
services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "8501:8501"
    networks:
      - mynetwork

  stockseeker-streamlit:
    build:
      context: .
      dockerfile: Dockerfile-streamlit
    ports:
      - "8502:8502"
    networks:
      - mynetwork

networks:
  mynetwork: