# Use the official Streamlit Docker image
FROM streamlit/streamlit:latest

# Set the working directory inside the container
WORKDIR /app

# Copy all necessary files to the container
COPY app.py /app
COPY requirements.txt /app
COPY config.toml /app
COPY credentials.toml /app
COPY saved_models /app/saved_models

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port where Streamlit runs
EXPOSE 8501

# Command to run the Streamlit app
CMD ["streamlit", "run", "app.py"]